import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { createServer } from "../../packages/server/dist/index.js";

test("dashboard ships responsive workbench contracts for dense operator pages", async () => {
  const dataRoot = fs.mkdtempSync(path.join(os.tmpdir(), "evopilot-dashboard-responsive-"));
  const server = createServer({
    dataRoot,
    runtimeMode: "debug",
    dashboardRoot: path.resolve("apps/dashboard")
  });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const address = server.address();
  const baseUrl = `http://127.0.0.1:${address.port}`;

  try {
    const html = await (await fetch(baseUrl)).text();
    const app = await (await fetch(`${baseUrl}/assets/app.js`)).text();
    const css = await (await fetch(`${baseUrl}/assets/styles.css`)).text();

    assert.match(html, /EvoPilot 控制台/);
    assert.match(app, /renderSaasTenantOverview/);
    assert.match(app, /renderSaasWorkspace/);
    assert.match(app, /renderSaasCredentialCenter/);
    assert.match(app, /renderTenantScopeBar/);
    assert.match(app, /saasScopeModel/);
    assert.match(app, /firstLoopLaunchSteps/);
    assert.match(app, /loopTemplateCards/);
    assert.match(app, /dashboardNextActions/);
    assert.match(app, /renderInlineLoopTemplates/);
    assert.match(app, /renderLoopEmptyAction/);
    assert.match(app, /renderHomeCommandCenter/);
    assert.match(app, /renderSimplifiedHome/);
    assert.match(app, /renderSourceToGaWizard/);
    assert.match(app, /renderSimplifiedLoopExecution/);
    assert.match(app, /renderSimplifiedRelease/);
    assert.match(app, /command-action/);
    assert.match(app, /navSections/);
    assert.match(app, /renderDiscoveryAndTargets/);
    assert.match(app, /renderLoopExecution/);
    assert.match(app, /renderEvaluationAndRelease/);
    assert.match(app, /renderLoopTargetRuntimePanel/);
    assert.match(app, /renderReleaseGuardrailPanel/);
    assert.match(app, /renderAutopilotCommandCenter/);
    assert.match(app, /renderHumanActionInbox/);
    assert.match(app, /renderGuidedOnboardingPanel/);
    assert.match(app, /renderVisualLoopRunCanvas/);
    assert.match(app, /sourceToGaModel/);
    assert.match(app, /bindSourceToGaMap/);
    assert.match(app, /renderReleaseCockpit/);
    assert.match(app, /renderProjectDetailWorkspace/);
    assert.match(app, /renderConnectorMarketplaceSettings/);
    assert.match(app, /connectorMarketplaceModel/);
    assert.match(app, /renderWorkflowCanvasEditor/);
    assert.match(app, /workflowCanvasNodes/);
    assert.match(app, /renderInteractiveAgentRunConsole/);
    assert.match(app, /interactiveConsoleEvents/);
    assert.match(app, /autopilotReadinessModel/);
    assert.match(app, /humanActionInboxModel/);
    assert.match(app, /normalizePage/);
    assert.match(app, /loopBacklogModel/);
    assert.match(app, /backlog-summary/);
    assert.match(app, /renderReleaseInspector/);
    assert.match(app, /renderGuidedHelpManual/);
    assert.match(app, /renderHelpRoleMap/);
    assert.match(app, /helpManualRoles/);
    assert.match(app, /helpManualScenarios/);
    assert.match(app, /helpManualUrl/);
    assert.match(app, /openHelpManual/);
    assert.match(app, /topHelpButton\.addEventListener\("click", openHelpManual\)/);
    assert.match(app, /const isHelpManual = state\.active === "帮助手册";/);
    assert.match(app, /document\.body\.classList\.toggle\("help-page-mode", isHelpManual\)/);
    assert.match(app, /isHelpManual \? "" : `\$\{renderAuthBar\(\)\}\$\{renderTenantScopeBar\(\)\}`/);
    assert.match(app, /release-inspector/);
    assert.match(app, /renderEmptyState/);
    assert.match(app, /renderStatusNotice/);
    assert.match(app, /renderLoadingSkeleton/);
    assert.match(app, /data-label="\$\{escapeHtml\(headers\[index\] \?\? ""\)\}"/);
    assert.match(css, /\.command-center/);
    assert.match(css, /\.tenant-scope-bar/);
    assert.match(css, /\.saas-hero/);
    assert.match(css, /\.first-loop-launchpad/);
    assert.match(css, /\.launch-step-grid/);
    assert.match(css, /\.loop-template-grid/);
    assert.match(css, /\.next-action-list/);
    assert.match(css, /\.loop-empty-template-strip/);
    assert.match(css, /\.action-empty/);
    assert.match(css, /\.saas-metric-grid/);
    assert.match(css, /\.workspace-control-plane/);
    assert.match(css, /\.credential-center/);
    assert.match(css, /\.vault-list/);
    assert.match(css, /\.source-ga-home/);
    assert.match(css, /\.source-ga-stepper/);
    assert.match(css, /\.source-ga-wizard-layout/);
    assert.match(css, /\.source-ga-loop-grid/);
    assert.match(css, /\.source-ga-release-hero/);
    assert.match(css, /\.nav-section/);
    assert.match(css, /\.page-brief/);
    assert.match(css, /\.autopilot-cockpit/);
    assert.match(css, /\.action-inbox/);
    assert.match(css, /\.onboarding-guide/);
    assert.match(css, /\.loop-canvas/);
    assert.match(css, /\.source-ga-workbench/);
    assert.match(css, /\.source-ga-map/);
    assert.match(css, /\.source-ga-node/);
    assert.match(css, /\.release-cockpit/);
    assert.match(css, /\.project-workspace/);
    assert.match(css, /\.connector-marketplace/);
    assert.match(css, /\.workflow-editor/);
    assert.match(css, /\.run-console/);
    assert.match(css, /\.workspace-tabs/);
    assert.match(css, /\.connector-grid/);
    assert.match(css, /\.workflow-node-board/);
    assert.match(css, /\.console-lines/);
    assert.match(css, /\.canvas-lane/);
    assert.match(css, /\.release-checklist/);
    assert.match(css, /\.provider-switcher/);
    assert.match(css, /\.field-kit-grid/);
    assert.match(css, /\.field-kit-card/);
    assert.match(css, /\.target-runtime-lists/);
    assert.match(css, /\.runtime-row/);
    assert.match(css, /\.backlog-summary/);
    assert.match(css, /\.release-inspector/);
    assert.match(css, /\.manual-scenario/);
    assert.match(css, /\.help-page-mode/);
    assert.match(css, /\.top-help-button/);
    assert.match(css, /\.help-doc-globalbar/);
    assert.match(css, /\.help-doc-search/);
    assert.match(css, /\.help-doc-main/);
    assert.match(css, /\.manual-doc-layout/);
    assert.match(css, /\.manual-doc-toc/);
    assert.match(css, /\.manual-doc-section/);
    assert.match(css, /\.manual-catalog-layout/);
    assert.match(css, /\.manual-catalog-tree/);
    assert.match(css, /\.manual-catalog-aside/);
    assert.match(css, /\.manual-doc-subnav/);
    assert.match(css, /\.manual-doc-footer/);
    assert.match(css, /\.manual-role-map/);
    assert.match(css, /\.manual-role-card/);
    assert.match(css, /\.manual-role-scenario-grid/);
    assert.match(css, /\.manual-permission-own/);
    assert.match(css, /\.manual-screenshot/);
    assert.match(css, /\.empty-state/);
    assert.match(css, /\.skeleton-panel/);
    assert.match(css, /@media \(max-width: 640px\)/);
    assert.match(css, /\.table-shell thead/);
    assert.match(css, /content: attr\(data-label\)/);
    assert.match(css, /grid-template-columns: 92px minmax\(0, 1fr\)/);
    assert.match(css, /\.release-inspector,\n  \.branch-strategy/);
  } finally {
    await new Promise((resolve) => server.close(resolve));
  }
});
