import { EVOPILOT_PRODUCT_VERSION_FALLBACK, SEMANTIC_EXECUTION_OPERATIONS, type SemanticExecutionOperation, type EvoPilotProjectSemanticOperation } from "@evopilot/contracts";
export type { EvoPilotLifecycleExecutorAdapterV1 as LifecycleExecutorAdapterV1 } from "@evopilot/contracts";

export interface McpEvidenceSignal {
  toolName: string;
  traceId?: string;
  status: "SUCCEEDED" | "FAILED" | "PARTIAL";
  message: string;
  attributes?: Record<string, unknown>;
}

export const EVOPILOT_LIFECYCLE_MCP_SCHEMA = "evopilot-lifecycle-mcp-surface/v1alpha1" as const;
export const EVOPILOT_ADAPTER_MCP_VERSION = EVOPILOT_PRODUCT_VERSION_FALLBACK;

export interface EvoPilotLifecycleMcpTool {
  name: string;
  description: string;
  method: "GET" | "POST" | "DELETE";
  path: string;
  authority: "NONE" | "EXACT_BINDING_DECISION" | "EXTERNAL_EXECUTION_RECEIPT";
  semanticOperation?: EvoPilotProjectSemanticOperation;
  executionOperation?: SemanticExecutionOperation | "capabilities";
}

export const EVOPILOT_LIFECYCLE_MCP_TOOLS: EvoPilotLifecycleMcpTool[] = [
  {name: "evopilot_semantic_execution_capabilities", description: "Discover finite Runtime execution operations; availability is not qualification or approval.", method: "GET", path: "/api/v1/projects/{projectId}/semantic-execution/capabilities", authority: "NONE", executionOperation: "capabilities"},
  ...SEMANTIC_EXECUTION_OPERATIONS.map(operation => ({name: `evopilot_semantic_execution_${operation}`, description:
    operation === "approveReview" ? "Submit explicit APPROVE for the exact business mapping review digest; never infer the user decision." :
    operation === "dispatch" ? "Request exact reviewed execution through the server-configured qualified adapter. Unknown outcomes must not be replayed. No completion authority." :
    operation === "collect" ? "Collect bounded evidence through the exact server-configured collector and active policy. No client facts, raw evidence output or completion authority." :
    operation === "commitStage" ? "Commit one pending stage only after fresh server-owned dual validation and explicit stage policy. Read stageReceipt after a lost response; never auto-advance or infer release authority." :
    operation === "completeTarget" ? "Complete a verified Target through fresh Runtime authority and typed package checks. Aggregate phase/GA closure and release are separate. Reconcile retained write claims; never retry automatically." :
    operation === "completeGoal" ? "Commit an exactly authorized Goal only after all required Target and declared phase receipts verify; no release, deployment or publication. Read goalReceipt after uncertainty." :
    operation === "completePhase" ? "Commit a verified aggregate phase package under exact current scoped phase policy. No Goal/GA closure or publication. Read phaseReceipt after uncertainty; never blindly replay." :
    ["stageReceipt", "completionReceipt", "completionStatus", "phaseReceipt", "goalReceipt"].includes(operation) ? "Read verified historical completion receipts or a digest-bound progress report. Raw DONE/GO flags are not evidence; no mutation or publication authority." :
    `Invoke Runtime-owned ${operation} against exact persisted semantic execution identity. No activation, completion or publication authority.`,
    method: "POST" as const, path: `/api/v1/projects/{projectId}/semantic-execution/${operation}`,
    authority: operation === "approveReview" ? "EXACT_BINDING_DECISION" as const : operation === "dispatch" ? "EXTERNAL_EXECUTION_RECEIPT" as const : "NONE" as const,
    executionOperation: operation})),
  { name: "evopilot_project_semantic_capabilities", description: "Negotiate Runtime-owned project semantic operations. Capability discovery is not execution or approval.", method: "GET", path: "/api/v1/projects/{projectId}/semantic-capabilities", authority: "NONE", semanticOperation: "capabilities" },
  { name: "evopilot_project_semantic_inspect", description: "Inspect the configured, permitted published semantic catalog without selecting or importing assets.", method: "GET", path: "/api/v1/projects/{projectId}/semantic-catalogs/{catalogId}", authority: "NONE", semanticOperation: "inspect" },
  { name: "evopilot_project_semantic_compatibility", description: "Check one exact ArtifactSet and HarnessBundle against current project access. Compatibility is not execution authority.", method: "GET", path: "/api/v1/projects/{projectId}/semantic-catalogs/{catalogId}/compatibility", authority: "NONE", semanticOperation: "compatibility" },
  { name: "evopilot_project_semantic_gap", description: "Read verified compatibility gap handoffs for one exact published pair. Review destinations are not defect attribution; no asset selection, producer mutation, approval or publication.", method: "GET", path: "/api/v1/projects/{projectId}/semantic-catalogs/{catalogId}/gap", authority: "NONE", semanticOperation: "gap" },
  { name: "evopilot_project_semantic_review", description: "Prepare a Runtime-owned immutable review for exact published selections. Never infers approval.", method: "POST", path: "/api/v1/projects/{projectId}/semantic-binding/reviews", authority: "NONE", semanticOperation: "review" },
  { name: "evopilot_project_semantic_approve", description: "Submit an explicit APPROVE decision for the exact reviewed digest. The scoped Runtime principal owns the decision; the binding is not activated for execution.", method: "POST", path: "/api/v1/projects/{projectId}/semantic-binding/approvals", authority: "EXACT_BINDING_DECISION", semanticOperation: "approve" },
  { name: "evopilot_project_semantic_binding", description: "Read the persisted project semantic binding and decision without replaying approval or activating a run.", method: "GET", path: "/api/v1/projects/{projectId}/semantic-binding", authority: "NONE", semanticOperation: "binding" },
  { name: "evopilot_project_semantic_activation", description: "Read current project selection, exact head and bounded transition history. Reconcile uncertain responses without replay. No execution authority.", method: "GET", path: "/api/v1/projects/{projectId}/semantic-binding/activation", authority: "NONE", semanticOperation: "activation" },
  { name: "evopilot_project_semantic_onboarding", description: "Read Runtime-owned semantic onboarding guidance in one explicitly selected Catalog. Preserve existing binding; distinguish compatible, ambiguous, missing and indeterminate choices. Never automatically select, approve or execute.", method: "GET", path: "/api/v1/projects/{projectId}/semantic-catalogs/{catalogId}/onboarding", authority: "NONE", semanticOperation: "onboarding" },
  { name: "evopilot_project_semantic_transitionReview", description: "Preview explicit ACTIVATE, MIGRATE or ROLLBACK against an exact head. MIGRATE names a review digest; ACTIVATE/ROLLBACK name binding digests. No implicit selection or approval.", method: "POST", path: "/api/v1/projects/{projectId}/semantic-binding/transition-reviews", authority: "NONE", semanticOperation: "transitionReview" },
  { name: "evopilot_project_semantic_transitionApprove", description: "Transmit explicit APPROVE for the exact transitionReviewDigest. Changes future-plan selection only; old runs retain their pins. No execution, asset publication or release authority.", method: "POST", path: "/api/v1/projects/{projectId}/semantic-binding/transition-approvals", authority: "EXACT_BINDING_DECISION", semanticOperation: "transitionApprove" },
  { name: "evopilot_runtime_readiness_inspect", description: "Inspect Runtime-owned first-run LLM readiness and the finite next repair action.", method: "GET", path: "/api/v1/runtime-readiness", authority: "NONE" },
  { name: "evopilot_llm_setup_protocol", description: "Read Runtime-owned setup and explicit administrator migration/bootstrap contracts. Metadata only; never submits or receives raw credentials or authorizes bootstrap.", method: "GET", path: "/api/v1/runtime-readiness/setup-protocol", authority: "NONE" },
  { name: "evopilot_llm_provider_discover", description: "Discover provider-neutral LLM setup choices; no provider or model is selected by default.", method: "GET", path: "/api/v1/llm-providers", authority: "NONE" },
  { name: "evopilot_llm_profile_list", description: "List tenant/workspace-visible governed LLM profiles without exposing raw credentials.", method: "GET", path: "/api/v1/llm-profiles", authority: "NONE" },
  { name: "evopilot_llm_profile_inspect", description: "Inspect one governed LLM profile and its redacted SecretRef-only configuration.", method: "GET", path: "/api/v1/llm-profiles/{profileId}", authority: "NONE" },
  { name: "evopilot_llm_profile_upsert", description: "Create or revise one governed LLM profile from an existing SecretRef; raw credentials are forbidden.", method: "POST", path: "/api/v1/llm-profiles", authority: "NONE" },
  { name: "evopilot_llm_profile_preflight", description: "Run a server-side live provider preflight for one exact governed LLM profile.", method: "POST", path: "/api/v1/llm-profiles/{profileId}/preflight", authority: "NONE" },
  { name: "evopilot_workspace_llm_default_bind", description: "Bind one live-preflight READY workspace profile as the explicit Runtime default.", method: "POST", path: "/api/v1/runtime-readiness/workspace-default", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_runtime_readiness_repair", description: "Reconcile readiness after explicit profile, SecretRef, or provider repair without selecting a fallback.", method: "POST", path: "/api/v1/runtime-readiness/repair", authority: "NONE" },
  { name: "evopilot_resource_list", description: "List independently versioned governed resources without loading a legacy Codex Suite.", method: "GET", path: "/api/v1/evolution-resources", authority: "NONE" },
  { name: "evopilot_resource_inspect", description: "Inspect one exact governed resource revision and immutable source provenance.", method: "GET", path: "/api/v1/evolution-resources/{kind}/{resourceId}", authority: "NONE" },
  { name: "evopilot_resource_register", description: "Register one immutable declarative resource; registration is not activation or approval.", method: "POST", path: "/api/v1/evolution-resources", authority: "NONE" },
  { name: "evopilot_resource_diff", description: "Semantically compare two resource revisions and determine Runtime/Expert version impact.", method: "GET", path: "/api/v1/evolution-resources/{kind}/{resourceId}/diff", authority: "NONE" },
  { name: "evopilot_resource_activate", description: "Activate or roll back to one exact immutable resource revision with owning-human evidence.", method: "POST", path: "/api/v1/evolution-resources/{kind}/{resourceId}/activate", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_capability_inventory_validate", description: "Validate exact latest Suite provenance and one explicit disposition for every frozen capability.", method: "POST", path: "/api/v1/governed-evolution/capability-inventory/validate", authority: "NONE" },
  { name: "evopilot_action_provider_qualify", description: "Qualify typed provider actions, SecretRefs, receipts, rollback, and authority limits; arbitrary shell is forbidden.", method: "POST", path: "/api/v1/governed-evolution/action-providers/qualify", authority: "NONE" },
  { name: "evopilot_agent_runtime_list", description: "Discover tenant/workspace external Agent Runtime profiles without conflating them with Agent Hosts.", method: "GET", path: "/api/v1/governed-evolution/agent-runtimes", authority: "NONE" },
  { name: "evopilot_agent_runtime_qualify", description: "Negotiate capabilities and produce an exact qualification report for an external Agent Runtime profile.", method: "POST", path: "/api/v1/governed-evolution/agent-runtimes/qualify", authority: "NONE" },
  { name: "evopilot_governance_pack_evaluate", description: "Evaluate declarative governance gates against exact binding evidence without inferring approval.", method: "POST", path: "/api/v1/governed-evolution/governance/evaluate", authority: "NONE" },
  { name: "evopilot_remediation_campaign_start", description: "Start a digest-bound, durable, bounded autonomous remediation campaign.", method: "POST", path: "/api/v1/governed-evolution/remediation-campaigns", authority: "NONE" },
  { name: "evopilot_remediation_campaign_inspect", description: "Inspect current remediation lineage, receipts, budget, and exact stop state.", method: "GET", path: "/api/v1/governed-evolution/remediation-campaigns/{campaignId}", authority: "NONE" },
  { name: "evopilot_remediation_campaign_decide", description: "Classify one failure and persist an automatic continuation or exact human stop decision.", method: "POST", path: "/api/v1/governed-evolution/remediation-campaigns/{campaignId}/decide", authority: "NONE" },
  { name: "evopilot_remediation_campaign_resume", description: "Resume a campaign waiting at one exact human decision and campaign digest.", method: "POST", path: "/api/v1/governed-evolution/remediation-campaigns/{campaignId}/resume", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_remediation_campaign_cancel", description: "Cancel one exact non-verified campaign with auditable human evidence.", method: "POST", path: "/api/v1/governed-evolution/remediation-campaigns/{campaignId}/cancel", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_lifecycle_observation_record", description: "Record exact Runtime, project, Lifecycle, HarnessBundle, GoalTarget, Host, Provider, environment, authority, evaluator, scorer, and evidence-bound Pipeline observations.", method: "POST", path: "/api/v1/controlled-lifecycle/observations", authority: "NONE" },
  { name: "evopilot_lifecycle_observation_inspect", description: "Inspect one immutable Pipeline observation and its deterministic gap classification.", method: "GET", path: "/api/v1/controlled-lifecycle/observations/{observationId}", authority: "NONE" },
  { name: "evopilot_lifecycle_gap_classify", description: "Classify a Pipeline observation as a declarative successor, governed-resource successor, generic Runtime primitive, Expert guidance gap, or no action without mutating active state.", method: "POST", path: "/api/v1/controlled-lifecycle/observations/{observationId}/classify", authority: "NONE" },
  { name: "evopilot_lifecycle_successor_propose", description: "Create an immutable Lifecycle successor proposal with semantic, authority, dependency, compatibility, impact, migration, experiment, monitoring, rollback, and provenance diffs.", method: "POST", path: "/api/v1/controlled-lifecycle/successors", authority: "NONE" },
  { name: "evopilot_lifecycle_successor_inspect", description: "Inspect one exact immutable Lifecycle successor proposal without activating it.", method: "GET", path: "/api/v1/controlled-lifecycle/successors/{proposalId}", authority: "NONE" },
  { name: "evopilot_lifecycle_experiment_evaluate", description: "Evaluate Champion and Challenger only under an identical governed context and stratify any mismatch instead of mixing evidence.", method: "POST", path: "/api/v1/controlled-lifecycle/experiments", authority: "NONE" },
  { name: "evopilot_lifecycle_activation_decide", description: "Apply an exact active safe-activation policy; auto-activate future runs only when every preauthorized predicate passes, otherwise return a bound human decision or rejection.", method: "POST", path: "/api/v1/controlled-lifecycle/activation-decisions", authority: "NONE" },
  { name: "evopilot_lifecycle_monitoring_evaluate", description: "Evaluate declared post-activation health signals and perform receipt-safe deterministic rollback without rebinding active runs or replaying uncertain mutations.", method: "POST", path: "/api/v1/controlled-lifecycle/monitoring/evaluate", authority: "NONE" },
  { name: "evopilot_generic_primitive_target_propose", description: "Create a digest-bound Runtime or Expert Target proposal for a missing project-neutral primitive and block project-specific Core branching.", method: "POST", path: "/api/v1/controlled-lifecycle/target-proposals", authority: "NONE" },
  { name: "evopilot_project_list", description: "List scoped connected projects from Runtime.", method: "GET", path: "/api/v1/projects", authority: "NONE" },
  { name: "evopilot_project_inspect", description: "Inspect one connected project from Runtime under current scope.", method: "GET", path: "/api/v1/projects/{projectId}", authority: "NONE" },
  { name: "evopilot_project_onboarding_plan", description: "Inspect source, DevOps and LLM prerequisites for explicit project connection inputs; this may read the selected repository but does not register or run it.", method: "POST", path: "/api/v1/onboarding/project/checklist", authority: "NONE" },
  { name: "evopilot_project_register", description: "Connect the explicitly selected project through Runtime validation and permissions; registration does not approve or run a Goal.", method: "POST", path: "/api/v1/projects", authority: "NONE" },
  { name: "evopilot_project_readiness", description: "Read the connected project onboarding checklist and finite blockers from Runtime.", method: "GET", path: "/api/v1/projects/{projectId}/onboarding-checklist", authority: "NONE" },
  { name: "evopilot_project_definition_list", description: "List versioned declarative EvolutionProjectDefinitions.", method: "GET", path: "/api/v1/evolution-project-definitions", authority: "NONE" },
  { name: "evopilot_project_definition_inspect", description: "Inspect one exact declarative project definition.", method: "GET", path: "/api/v1/evolution-project-definitions/{projectDefinitionId}", authority: "NONE" },
  { name: "evopilot_project_definition_register", description: "Register one immutable human-reviewable project definition; configuration is not approval.", method: "POST", path: "/api/v1/evolution-project-definitions", authority: "NONE" },
  { name: "evopilot_project_definition_discover", description: "Discover project facts and return Runtime-owned typed questions without collecting raw secrets.", method: "POST", path: "/api/v1/evolution-project-definitions/discover", authority: "NONE" },
  { name: "evopilot_project_definition_diff", description: "Compare two immutable project-definition revisions and show selective impact.", method: "GET", path: "/api/v1/evolution-project-definitions/{projectDefinitionId}/diff", authority: "NONE" },
  { name: "evopilot_project_definition_activate", description: "Activate or roll back to one exact immutable project-definition revision.", method: "POST", path: "/api/v1/evolution-project-definitions/{projectDefinitionId}/activate", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_project_definition_rollback", description: "Roll back future project-definition selection to an exact retained revision with reviewed digest and current-definition concurrency checks.", method: "POST", path: "/api/v1/evolution-project-definitions/{projectDefinitionId}/rollback", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_governed_evolution_plan", description: "Resolve Project plus GoalTarget to one published HarnessBundle, compose its open Lifecycle, and create an immutable HarnessExecutionBinding.", method: "POST", path: "/api/v1/governed-evolution/plan", authority: "NONE" },
  { name: "evopilot_governed_evolution_run", description: "Create a Lifecycle run from one exact HarnessExecutionBinding; it does not authorize execution.", method: "POST", path: "/api/v1/governed-evolution/runs", authority: "NONE" },
  { name: "evopilot_governed_evolution_revalidate", description: "Revalidate an exact HarnessExecutionBinding before start, resume, retry, or Loop iteration.", method: "POST", path: "/api/v1/governed-evolution/revalidate", authority: "NONE" },
  { name: "evopilot_recovery_decide", description: "Classify a failure and return the bounded automatic or human recovery boundary.", method: "POST", path: "/api/v1/governed-evolution/recovery/decide", authority: "NONE" },
  { name: "evopilot_automation_registry_inspect", description: "Inspect Automation Registry proposals and active, revoked, or expired rules.", method: "GET", path: "/api/v1/automation-registry", authority: "NONE" },
  { name: "evopilot_automation_rule_propose", description: "Create an inspectable immutable proposal for one reusable safe recovery rule.", method: "POST", path: "/api/v1/automation-registry/proposals", authority: "NONE" },
  { name: "evopilot_automation_rule_activate", description: "Activate one exact Automation Registry proposal after the user's digest-bound decision.", method: "POST", path: "/api/v1/automation-registry/{ruleId}/activate", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_automation_rule_revoke", description: "Revoke an Automation Registry rule with exact human evidence.", method: "POST", path: "/api/v1/automation-registry/{ruleId}/revoke", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_interaction_render", description: "Render a Runtime-owned Human Interaction Protocol object for any compatible Expert or headless client.", method: "POST", path: "/api/v1/interactions/render", authority: "NONE" },
  { name: "evopilot_lifecycle_list", description: "List tenant/workspace Lifecycle revisions, state, and active pointers from Runtime-owned truth.", method: "GET", path: "/api/v1/lifecycles", authority: "NONE" },
  { name: "evopilot_lifecycle_inspect", description: "Inspect one exact immutable Lifecycle revision, state, provenance, and active pointer.", method: "GET", path: "/api/v1/lifecycles/{lifecycleId}", authority: "NONE" },
  { name: "evopilot_lifecycle_register", description: "Create or register an immutable human-readable Lifecycle revision; registration never activates it.", method: "POST", path: "/api/v1/lifecycles", authority: "NONE" },
  { name: "evopilot_lifecycle_diff", description: "Compare two immutable Lifecycle revisions and report exact semantic and future-planning impact.", method: "GET", path: "/api/v1/lifecycles/{lifecycleId}/diff", authority: "NONE" },
  { name: "evopilot_lifecycle_activate", description: "Move the future-planning pointer to one exact Lifecycle revision using expected-active-digest concurrency.", method: "POST", path: "/api/v1/lifecycles/{lifecycleId}/activate", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_lifecycle_deactivate", description: "Deactivate one exact active Lifecycle pointer without mutating bound runs.", method: "POST", path: "/api/v1/lifecycles/{lifecycleId}/deactivate", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_lifecycle_archive", description: "Archive an inactive exact Lifecycle revision while preserving inspection and audit history.", method: "POST", path: "/api/v1/lifecycles/{lifecycleId}/archive", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_lifecycle_restore", description: "Restore an archived Lifecycle revision to inactive state without activating it.", method: "POST", path: "/api/v1/lifecycles/{lifecycleId}/restore", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_lifecycle_rollback", description: "Move the future-planning pointer back to one exact retained Lifecycle revision without rewriting history.", method: "POST", path: "/api/v1/lifecycles/{lifecycleId}/rollback", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_lifecycle_dependencies", description: "Inspect exact Lifecycle imports and dependents.", method: "GET", path: "/api/v1/lifecycles/{lifecycleId}/dependencies", authority: "NONE" },
  { name: "evopilot_lifecycle_usage", description: "Inspect immutable plan and run references to Lifecycle revisions.", method: "GET", path: "/api/v1/lifecycles/{lifecycleId}/usage", authority: "NONE" },
  { name: "evopilot_lifecycle_audit", description: "Inspect immutable Lifecycle Registry audit history.", method: "GET", path: "/api/v1/lifecycles/{lifecycleId}/audit", authority: "NONE" },
  { name: "evopilot_lifecycle_delete_draft", description: "Physically delete only an unreferenced, never-active registered draft revision.", method: "DELETE", path: "/api/v1/lifecycles/{lifecycleId}", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_lifecycle_resolve", description: "Resolve an explicit or metadata-matched Lifecycle without project-specific Engine branches.", method: "POST", path: "/api/v1/lifecycles/resolve", authority: "NONE" },
  { name: "evopilot_lifecycle_resolve_inputs", description: "Resolve declared and discovered inputs and return only the next unresolved question.", method: "POST", path: "/api/v1/lifecycles/resolve-inputs", authority: "NONE" },
  { name: "evopilot_lifecycle_start", description: "Create a digest-bound Lifecycle run without authorizing execution.", method: "POST", path: "/api/v1/lifecycle-runs", authority: "NONE" },
  { name: "evopilot_lifecycle_run_list", description: "List Lifecycle runs in the authenticated tenant and workspace.", method: "GET", path: "/api/v1/lifecycle-runs", authority: "NONE" },
  { name: "evopilot_lifecycle_run_inspect", description: "Inspect one Lifecycle run and its current immutable binding.", method: "GET", path: "/api/v1/lifecycle-runs/{runId}", authority: "NONE" },
  { name: "evopilot_lifecycle_answer", description: "Answer declared input questions; answers never imply approval.", method: "POST", path: "/api/v1/lifecycle-runs/{runId}/answer", authority: "NONE" },
  { name: "evopilot_lifecycle_finalize_binding", description: "Finalize one immutable Lifecycle execution binding without approving it.", method: "POST", path: "/api/v1/lifecycle-runs/{runId}/finalize-binding", authority: "NONE" },
  { name: "evopilot_lifecycle_authorize", description: "Record an explicit decision for one exact immutable binding digest.", method: "POST", path: "/api/v1/lifecycle-runs/{runId}/authorize", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_lifecycle_decision", description: "Record an explicit human decision at the exact pending Lifecycle stage and binding digest.", method: "POST", path: "/api/v1/lifecycle-runs/{runId}/decision", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_lifecycle_cancel", description: "Cancel a non-terminal Lifecycle run against its exact binding digest with auditable human evidence.", method: "POST", path: "/api/v1/lifecycle-runs/{runId}/cancel", authority: "EXACT_BINDING_DECISION" },
  { name: "evopilot_lifecycle_advance", description: "Advance automatic stages until the next real authority or external execution boundary.", method: "POST", path: "/api/v1/lifecycle-runs/{runId}/advance", authority: "NONE" },
  { name: "evopilot_lifecycle_record_external_result", description: "Record a reviewed third-party Agent execution receipt for the exact pending request.", method: "POST", path: "/api/v1/lifecycle-runs/{runId}/external-result", authority: "EXTERNAL_EXECUTION_RECEIPT" },
  { name: "evopilot_lifecycle_export_feedback", description: "Create an approved, strict-redacted, immutable private feedback package without mutating Harness assets.", method: "POST", path: "/api/v1/lifecycle-runs/{runId}/feedback", authority: "EXACT_BINDING_DECISION" }
];
